### ISSUE TITLE
What is the url for USPS dataset?

### ISSUE THREAD

**Issue by leehomyc** [mingyuliutw/CoGAN#4]
I cannot find the download link. Also, the [link](https://raw.githubusercontent.com/mingyuliutw/CoGAN_PyTorch/master/data/uspssample/usps_28x28.pkl) I found somewhere else is not valid anymore.

**Comment by mingyuliutw** [comment]
@leehomyc Thanks for reporting I have checked in the file in /cogan_pytorch/data/uspssample/usps_28x28.pkl now.
